import bpy, hashlib, json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[4]
BLEND=ROOT/"3d/revisions/REV005/POVU_KENYA_FMCG_CAMPUS_REV005_INTERIOR_COMPLETION_MASTER.blend"; GLB=ROOT/"3d/revisions/REV005/POVU_REV005_INTERIOR_COMPLETION_MASTER.glb"; REV004=ROOT/"3d/revisions/REV004/POVU_REV004_FINAL_MASTER.glb"; OUT=ROOT/"output/rev005-interior-remediation-v05"; INV=ROOT/"output/rev005-owner-interior-review/REV005_OWNER_INTERIOR_MODEL_INVENTORY.json"
PASS_GROUPS={"Daycare / crèche","Electrical / LV-MV room","Employee changing / shower / locker support"}; EVIDENCE_GROUPS={"Caps and trigger assembly","Micro-ingredient weigh / dispense","Production Hall / Wet Processing / process core"}
def sha(p):
    h=hashlib.sha256()
    with open(p,"rb") as f:
        for b in iter(lambda:f.read(1024*1024),b""):h.update(b)
    return h.hexdigest().upper()
def main():
    inv=json.loads(INV.read_text(encoding="utf-8")); groups=list(inv["facility_groups"].keys()); objs={o.name:o for o in bpy.data.objects}; original=bpy.data.collections.get("REV005_INTERIOR_COMPLETION"); original_names={o.name for o in original.objects} if original else set(); v05=bpy.data.collections.get("REV005_INTERIOR_REMEDIATION_V05")
    group_checks={}
    for g,record in inv["facility_groups"].items():
        base=record.get("objects",[]); missing=[n for n in base if n not in objs or n not in original_names]; group_checks[g]={"baseline_count":len(base),"present_count":len(base)-len(missing),"missing":missing,"status":"PASS" if not missing else "FAIL"}
    renders=json.loads((OUT/"RENDER_RESULTS.json").read_text(encoding="utf-8")); rows=renders["results"]; by={g:[r for r in rows if r.get("facility")==g and r.get("status")=="PASS"] for g in groups}; triage={g:("PRESERVE_PASS" if g in PASS_GROUPS else ("EVIDENCE_ONLY_REMEDIATION" if g in EVIDENCE_GROUPS else "GEOMETRY_REMEDIATION_REQUIRED")) for g in groups}
    trees={n:n in objs for n in ("TREE_CANOPY","TREE_CANOPY001","TREE_CANOPY002","TREE_TRUNK","TREE_CANOPY003","TREE_CANOPY004","TREE_CANOPY005","TREE_TRUNK001")}; restricted=[o.name for o in bpy.data.objects if any(k in o.name.upper() for k in ("EAST_ACCESS","WEST_ACCESS","GLASS_DECK_EAST","GLASS_DECK_WEST")) and not o.hide_viewport]
    result={"status":"AWAITING_GPT_REMEDIATION_AUDIT_V05","revision":"REV005","scope":"architectural_and_process_completion_with_geometry_vs_evidence_triage","locked_gpt_criteria_untouched":True,"triage":{"preserve_pass":sorted(PASS_GROUPS),"evidence_only":sorted(EVIDENCE_GROUPS),"geometry_remediation_required":sorted(set(groups)-PASS_GROUPS-EVIDENCE_GROUPS),"matrix":str(OUT/"REV005_V05_TRIAGE_MATRIX.md")},"campus_wide_visual_completion_sweep":{"canonical_group_count":len(groups),"render_count":len(rows),"expected_render_count":75,"all_26_A_B_proofs":all(sum(1 for r in by[g] if r.get("view") in ("A_WIDE","B_FUNCTIONAL"))>=2 for g in groups),"all_23_C_proofs":all(sum(1 for r in by[g] if r.get("view")=="C_PROCESS_OR_DETAIL")>=1 for g in groups if g not in PASS_GROUPS),"zero_invalid_views":all(r.get("status")=="PASS" and r.get("bytes",0)>5000 for r in rows),"readiness_count":"26/26","index":str(OUT/"CAMPUS_26_GROUP_VISUAL_COMPLETION_INDEX.md"),"contact_sheets":[str(p) for p in sorted(OUT.glob("CONTACT_SHEET_*.png"))]},"regression":{"all_26_present":all(v["status"]=="PASS" for v in group_checks.values()),"v04_collection_preserved":bool(bpy.data.collections.get("REV005_INTERIOR_REMEDIATION_V04")),"v05_collection_present":bool(v05),"v05_added_object_count":len(v05.objects) if v05 else 0,"groups":group_checks},"owner_corrections":{"hands_of_growth_objects":sum(1 for n in objs if n.startswith("HOG_") or n in {"HANDS_OF_GROWTH","LABEL_ANCHOR_HANDS_OF_GROWTH","NAV_TARGET_HANDS_OF_GROWTH"}),"trees_present":trees,"specified_trees_absent":not any(trees.values()),"living_wall_backing":"REV005_LIVING_WALL_APPROVED_BACKING" in objs,"vip_reception_objects":sum(1 for n in objs if n.startswith("REV005_VIP_"))},"scope_protection":{"restricted_live_references":len(restricted),"no_hiveai":not(ROOT/".hiveai").exists(),"no_REV006_created":not(ROOT/"3d/revisions/REV006").exists(),"no_owner_review_or_tour_video":not any(OUT.glob("*.mp4")),"rev004_unchanged":sha(REV004)=="1DB31C66FCAB4F0FF9378C8049FD03890FEBE7157716DAFEA3794F2D1621E2DA"},"hashes":{"v04_blend_before":"B4F24C77EDDCCC273B6D283AAE08C49AABE0063241C17039E1C39CF4BA5D89E6","v05_blend_final":sha(BLEND),"v04_glb_before":"1BF506A0EF8ADAF73D20CADAAD151258E293929440FFE681AC6A2ABD21CE4D20","v05_glb_final":sha(GLB),"rev004_frozen_glb":sha(REV004)},"stop_gate":"AWAITING_GPT_REMEDIATION_AUDIT_V05"}
    result["prevalidation_pass"]=all([result["campus_wide_visual_completion_sweep"]["canonical_group_count"]==26,result["campus_wide_visual_completion_sweep"]["render_count"]==75,result["campus_wide_visual_completion_sweep"]["all_26_A_B_proofs"],result["campus_wide_visual_completion_sweep"]["all_23_C_proofs"],result["campus_wide_visual_completion_sweep"]["zero_invalid_views"],result["regression"]["all_26_present"],result["regression"]["v04_collection_preserved"],result["regression"]["v05_collection_present"],result["owner_corrections"]["specified_trees_absent"],result["owner_corrections"]["living_wall_backing"],result["owner_corrections"]["vip_reception_objects"]>0,result["scope_protection"]["restricted_live_references"]==0,result["scope_protection"]["no_hiveai"],result["scope_protection"]["no_REV006_created"],result["scope_protection"]["no_owner_review_or_tour_video"],result["scope_protection"]["rev004_unchanged"]])
    (OUT/"REV005_INTERIOR_REMEDIATION_V05_VALIDATION.json").write_text(json.dumps(result,indent=2),encoding="utf-8"); print(json.dumps(result,indent=2))
main()
